spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audio_memes
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

auth:
  jwt:
    issuer: audio-playback-api
    audience: audio-playback-api
    access-token-lifetime: 15m