spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/audio_memes
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

auth:
  jwt:
    issuer: audio-playback-api
    audience: audio-playback-api
    access-token-lifetime: 15m
  google:
    client-id: ${GOOGLE_CLIENT_ID}